### ISSUE TITLE
Unique names across all physical resources?

### ISSUE THREAD

**Issue by rheinheimer** [hydraplatform/hydra-base#59]
Should resource names be unique between all resources, regardless of type (node or link)?  I am converting some generic nodes to Pywr Links, but this causes an issue in Pywr if a Hydra link happens to share a name with one of those generic nodes. I can of course easily enforce this on my end, just wondering if this is an issue generally that should be addressed at the Hydra Base level.

**Comment by knoxsp** [comment]
Uniqueness is only between nodes or links. Nodes and links can have the
same name. This is only enforced by table constraints, so I cant see how
adding a link with the same name as a node would be a problem

**Comment by rheinheimer** [comment]
To clarify: The issue is really in Pywr, in which both links and nodes from Hydra may be converted into Pywr "Nodes" (a Hydra link could be converted to a Pywr "Link", which is a subclass of "Node", at least as I'm implementing it to constrain flows in pipelines, etc.).

So either this is resolved in Hydra (could cause significant overhead?), or Pywr (have unique names only for specific Node subclass types), or by the user, e.g., by appending " [node]" or " [link]" to the resource name to ensure uniqueness.

@jetuk any thoughts? If I'm the only one with this issue, the last option should hopefully work.

**Comment by knoxsp** [comment]
That does clarify. This has been discussed, and is not considered a hydra
problem, as the constraint is one of the application - using nodes as
'links'. A naming convention within the translation to pywr makes the most
sense in this application in my opinion.

**Comment by jetuk** [comment]
The solution we've used is to retain `pywr.nodes.Link` as a Hydra node. It's more of a junction node. Pywr edges contain no information, not even a name, so this is just ignored. Currently this means in hydra links (i.e. pywr edges) have no attributes. They merely exist to describe network connectivity.

Just because they have same name (i.e. link) doesn't mean they need to map to one another IMO. I have argued against this sort of magic in order to keep as a close to 1:1 mapping between hydra and pywr as possible. I.e. all pywr nodes are hydra nodes, and hydra links (pywr edges) are dumb. Not everyone agrees :smile:

**Comment by rheinheimer** [comment]
@jetuk Thanks. I certainly don't agree that links aka edges are "dumb" (a lot can happen in a river!), but in fact I didn't realize I could map links to nameless edges. In this case, I think this is a user issue. If links are mapped to pywr.nodes.Link, then it's easy enough to make names unique. Anyway, clearly not a Hydra issue, so closing.
